Repository StenopePHP/Stenope, pull requests merged in 2021-05, with the labels that each got.

#83 Fix LastModifiedProcessor
  src/Processor/LastModifiedProcessor.php
Labels: enhancement

#89 [Doc] Fix build & add CI check on PR
  .github/workflows/build_static.yaml
  .github/workflows/ci.yaml
Labels: bug, documentation

#86 Generate table of content for easier navigation in documentation pages
  config/services.php
  doc/app/assets/styles/_responsive.scss
  doc/app/assets/styles/_table-of-content.scss
  doc/app/assets/styles/style.scss
  doc/app/composer.lock
  doc/app/config/services.yaml
  doc/app/src/Model/Page.php
  doc/app/templates/base.html.twig
  doc/app/templates/component/table_of_content.html.twig
  doc/app/templates/doc/page.html.twig
  src/Processor/TableOfContentProcessor.php
  src/TableOfContent/CrawlerTableOfContentGenerator.php
  src/TableOfContent/Headline.php
  tests/Unit/TableOfContent/CrawlerTableOfContentGeneratorTest.php
Labels: enhancement

#92 Fix assets processor for schemes like mailto:
  src/Service/AssetUtils.php
  tests/Unit/Service/AssetsUtilsTest.php
Labels: bug

#93 Fix doc anchors: Asset processor should not process anchors
  doc/app/Makefile
  src/Service/AssetUtils.php
  tests/Unit/Service/AssetsUtilsTest.php
Labels: bug
